/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './auth.module';
import * as i2 from './signup.component.ngfactory';
import * as i3 from './signin.component.ngfactory';
import * as i4 from './logout.component.ngfactory';
import * as i5 from '@angular/common';
import * as i6 from '@angular/forms';
import * as i7 from '@angular/router';
import * as i8 from './signup.component';
import * as i9 from './signin.component';
import * as i10 from './logout.component';
export const AuthModuleNgFactory:i0.NgModuleFactory<i1.AuthModule> = i0.ɵcmf(i1.AuthModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.SignupComponentNgFactory,i3.SigninComponentNgFactory,i4.LogoutComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i5.NgLocalization,
          i5.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i6.FormBuilder,i6.FormBuilder,
          ([] as any[])),i0.ɵmpd(4608,i6.ɵi,i6.ɵi,([] as any[])),i0.ɵmpd(512,i5.CommonModule,
          i5.CommonModule,([] as any[])),i0.ɵmpd(512,i6.ɵbc,i6.ɵbc,([] as any[])),
          i0.ɵmpd(512,i6.ReactiveFormsModule,i6.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i7.RouterModule,i7.RouterModule,[[2,i7.ɵa],[2,i7.Router]]),i0.ɵmpd(512,
              i1.AuthModule,i1.AuthModule,([] as any[])),i0.ɵmpd(1024,i7.ROUTES,() => {
            return [[{path:'',redirectTo:'signin',pathMatch:'full'},{path:'signup',
                component:i8.SignupComponent},{path:'signin',component:i9.SigninComponent},
                {path:'logout',component:i10.LogoutComponent}]];
          },([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbWpyaGEvRG9jdW1lbnRzL0RvY3VtZW50cy9EZXZlbG9wbWVudC9Sb2IvQmFjay1lbmQvT2xvcmktc2VydmVyL2Fzc2V0cy9hcHAvYXV0aC9hdXRoLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9tanJoYS9Eb2N1bWVudHMvRG9jdW1lbnRzL0RldmVsb3BtZW50L1JvYi9CYWNrLWVuZC9PbG9yaS1zZXJ2ZXIvYXNzZXRzL2FwcC9hdXRoL2F1dGgubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
