/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './logout.component';
import * as i2 from './auth.service';
import * as i3 from '@angular/router';
const styles_LogoutComponent:any[] = ([] as any[]);
export const RenderType_LogoutComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_LogoutComponent,data:{}});
export function View_LogoutComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted((null as any),['\n      '])),(_l()(),i0.ɵeld(0,
      (null as any),(null as any),4,'div',[['class','col-md-8 col-md-offset-2']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted((null as any),
      ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'button',[['class',
      'btn btn-danger']],(null as any),[[(null as any),'click']],(_v,en,$event) => {
    var ad:boolean = true;
    var _co:i1.LogoutComponent = _v.component;
    if (('click' === en)) {
      const pd_0:any = ((<any>_co.onLogout()) !== false);
      ad = (pd_0 && ad);
    }
    return ad;
  },(null as any),(null as any))),(_l()(),i0.ɵted((null as any),['Logout'])),(_l()(),
      i0.ɵted((null as any),['\n      '])),(_l()(),i0.ɵted((null as any),['\n    ']))],
      (null as any),(null as any));
}
export function View_LogoutComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'app-logout',([] as any[]),
      (null as any),(null as any),(null as any),View_LogoutComponent_0,RenderType_LogoutComponent)),
      i0.ɵdid(49152,(null as any),0,i1.LogoutComponent,[i2.AuthService,i3.Router],
          (null as any),(null as any))],(null as any),(null as any));
}
export const LogoutComponentNgFactory:i0.ComponentFactory<i1.LogoutComponent> = i0.ɵccf('app-logout',
    i1.LogoutComponent,View_LogoutComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvbWpyaGEvRG9jdW1lbnRzL0RvY3VtZW50cy9EZXZlbG9wbWVudC9Sb2IvQmFjay1lbmQvT2xvcmktc2VydmVyL2Fzc2V0cy9hcHAvYXV0aC9sb2dvdXQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL21qcmhhL0RvY3VtZW50cy9Eb2N1bWVudHMvRGV2ZWxvcG1lbnQvUm9iL0JhY2stZW5kL09sb3JpLXNlcnZlci9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL21qcmhhL0RvY3VtZW50cy9Eb2N1bWVudHMvRGV2ZWxvcG1lbnQvUm9iL0JhY2stZW5kL09sb3JpLXNlcnZlci9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnQuaHRtbCIsIm5nOi8vL0M6L1VzZXJzL21qcmhhL0RvY3VtZW50cy9Eb2N1bWVudHMvRGV2ZWxvcG1lbnQvUm9iL0JhY2stZW5kL09sb3JpLXNlcnZlci9hc3NldHMvYXBwL2F1dGgvbG9nb3V0LmNvbXBvbmVudC50cy5Mb2dvdXRDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICAgIDxkaXYgY2xhc3M9XCJjb2wtbWQtOCBjb2wtbWQtb2Zmc2V0LTJcIj5cbiAgICAgICAgPGJ1dHRvbiBjbGFzcz1cImJ0biBidG4tZGFuZ2VyXCIgKGNsaWNrKT1cIm9uTG9nb3V0KClcIj5Mb2dvdXQ8L2J1dHRvbj5cbiAgICAgIDwvZGl2PlxuICAgICIsIjxhcHAtbG9nb3V0PjwvYXBwLWxvZ291dD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBLDZDQUNNO01BQUE7TUFBQSwwREFBc0M7TUFBQSxpQkFDcEM7TUFBQTtJQUFBO0lBQUE7SUFBK0I7TUFBQTtNQUFBO0lBQUE7SUFBL0I7RUFBQSxnQ0FBb0QsMkNBQWU7YUFBQSw4QkFDL0Q7Ozs7b0JDSFo7TUFBQTthQUFBO1VBQUE7OzsifQ==
